### ISSUE TITLE
urllib3 does not work with boto3

### ISSUE THREAD

**Issue by camerondavison** [open-telemetry/opentelemetry-python-contrib#1235]
I put the stack trace, my poetry file, and an example python script. but after instrumenting urllib3 boto3 does not work.

https://gist.github.com/camerondavison/010b2cad69dd4bf307a77fa1f0b2549e

It looks like 
```
Traceback (most recent call last):
  File "/Users/cameron/Library/Caches/pypoetry/virtualenvs/instrument-play-SYEDf4cJ-py3.9/lib/python3.9/site-packages/botocore/httpsession.py", line 448, in send
    urllib_response = conn.urlopen(
  File "/Users/cameron/Library/Caches/pypoetry/virtualenvs/instrument-play-SYEDf4cJ-py3.9/lib/python3.9/site-packages/opentelemetry/instrumentation/urllib3/__init__.py", line 214, in instrumented_urlopen
    request_size = 0 if body is None else len(body)
TypeError: object of type '_io.BytesIO' has no len()
```
we just need to look at the body and call a different method for length if it is a BytesIO

**Comment by camerondavison** [comment]
It seems like it works if i add botocore instrumentation, which I imagine is because it suppresses instrumentation after the top level boto call

**Comment by vishal-ramesh2** [comment]
I am also facing this issue. Is there a way to fix this?

**Comment by ocelotl** [comment]
I asked Claude to review this issue and Claude suggests it be closed with this explanation:

> `len(body)` crash fixed; `_get_body_size()` handles `io.BytesIO` via `getbuffer().nbytes`.
>
> Proof in `main`: [`urllib3/__init__.py#L584-L585`](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/94e851dfe333d47fdb52edb82635330668af284e/instrumentation/opentelemetry-instrumentation-urllib3/src/opentelemetry/instrumentation/urllib3/__init__.py#L584-L585)

To guard against a mistaken suggestion, Claude then independently re-verified this conclusion:

> Verified: `urllib3/__init__.py` `_get_body_size()` handles `io.BytesIO` via `getbuffer().nbytes`, so the boto3 `len(body)` crash is fixed.

Claude evaluated this issue with high confidence that it can be closed.

Claude has classified this issue as already resolved (the requested fix or feature has already shipped).

The intention of this comment is to make it easier for a human being to review this issue before making a decision.
