### ISSUE TITLE
FastAPI integration doesn't work by the error ModuleNotFoundError: No module named 'opentelemetry.metrics' 

### ISSUE THREAD

**Issue by DAMACANER** [open-telemetry/opentelemetry-python-contrib#1775]
https://github.com/open-telemetry/opentelemetry-python/issues/3290

**Comment by shalevr** [comment]
It looks like you have conflicts with the sdk and instrumentation versions,
Work with the latest version if you can

**Comment by DAMACANER** [comment]
@shalevr I just installed them with pip install, no specific version.

**Comment by shalevr** [comment]
I got 
opentelemetry-api==1.17.0
opentelemetry-sdk==1.17.0
when I pip install opentelemetry-sdk, can you try again with a new Python environment?

**Comment by DAMACANER** [comment]
@shalevr 

Did:

```
pip install opentelemetry-api
pip install opentelemetry-sdk
pip install opentelemetry-exporter-jaeger
pip install opentelemetry-instrumentation-fastapi
```

and shell output of `pip freeze`:

```shell
anyio==3.6.2
asgiref==3.6.0
Deprecated==1.2.13
fastapi==0.95.1
googleapis-common-protos==1.56.2
grpcio==1.54.0
idna==3.4
importlib-metadata==6.0.1
opentelemetry-api==1.17.0
opentelemetry-exporter-jaeger==1.17.0
opentelemetry-exporter-jaeger-proto-grpc==1.17.0
opentelemetry-exporter-jaeger-thrift==1.17.0
opentelemetry-instrumentation==0.38b0
opentelemetry-instrumentation-asgi==0.38b0
opentelemetry-instrumentation-fastapi==0.38b0
opentelemetry-sdk==1.17.0
opentelemetry-semantic-conventions==0.38b0
opentelemetry-util-http==0.38b0
protobuf==3.20.3
pydantic==1.10.7
six==1.16.0
sniffio==1.3.0
starlette==0.26.1
thrift==0.16.0
typing_extensions==4.5.0
wrapt==1.15.0
zipp==3.15.0
```

all is well, but I still get:

```shell
(venv) caner@caner-Nitro-AN515-44:~/PycharmProjects/asd$ uvicorn main:app
Traceback (most recent call last):
  File "/home/caner/.local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/caner/.local/lib/python3.10/site-packages/uvicorn/main.py", line 407, in main
    run(
  File "/home/caner/.local/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/caner/.local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/caner/.local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/caner/.local/lib/python3.10/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/caner/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/caner/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/caner/PycharmProjects/asd/./main.py", line 4, in <module>
    from opentelemetry.exporter.jaeger.thrift import JaegerExporter
ModuleNotFoundError: No module named 'opentelemetry'
```

with literally the same code I specified.

**Comment by DAMACANER** [comment]
Last problem caused by version is due to JetBrains downloading an old version of the package when I download from here.

![image](https://user-images.githubusercontent.com/92731060/235349347-e7462da2-0eca-44ca-b252-edc698f46930.png)

**Comment by shalevr** [comment]
Ok, now you got the latest version and the error is different
This issue is with your env, please follow the documentation

**Comment by DAMACANER** [comment]
@shalevr https://opentelemetry.io/docs/instrumentation/python/#installation it only guides me with pip installations? sorry for being trouble.

**Comment by DAMACANER** [comment]
I used https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/opentelemetry-instrumentation#opentelemetry-bootstrap installation yet I still get same traceback.

**Comment by srikanthccv** [comment]
This is most likely an issue with your virtual environments.

**Comment by DAMACANER** [comment]
Thanks for the help everything works as expected.
