### ISSUE TITLE
KeyError: 'wsgi.url_scheme' 

### ISSUE THREAD

**Issue by OmarEltamasehy** [open-telemetry/opentelemetry-python-contrib#185]
Hi,
Appreciate your support as we try to use DjangoInstrumentor().instrument()
after importing opentelemetry.instrumentation.django as the below 
from opentelemetry.instrumentation.django import DjangoInstrumentor
and we are using django_channels dev server in my project but unfortunately, we faced the below issue and we tried to set "wsgi.url_scheme" by our self in python3.8/site-packages/opentelemetry/instrumentation/django/middleware.py and it is ok so please advice if there is another solution to do.

### My environment:
Django version 3.1.2
python version 3.8

### sever error log 
Traceback (most recent call last):
  File "/home/omar/workspace/testapp/testapp/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/omar/workspace/testapp/testapp/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "/home/omar/workspace/testapp/testapp/venv/lib/python3.8/site-packages/opentelemetry/instrumentation/django/middleware.py", line 140, in process_request
    attributes = collect_request_attributes(environ)
  File "/home/omar/workspace/testapp/testapp/venv/lib/python3.8/site-packages/opentelemetry/instrumentation/wsgi/__init__.py", line 122, in collect_request_attributes
    result["http.url"] = wsgiref_util.request_uri(environ)
  File "/usr/lib/python3.8/wsgiref/util.py", line 72, in request_uri
    url = application_uri(environ)
  File "/usr/lib/python3.8/wsgiref/util.py", line 52, in application_uri
    url = environ['wsgi.url_scheme']+'://'
KeyError: 'wsgi.url_scheme'
[public ERROR  ] Internal Server Error: /
Traceback (most recent call last):
  File "/home/omar/workspace/testapp/testapp/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/omar/workspace/testapp/testapp/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "/home/omar/workspace/testapp/testapp/venv/lib/python3.8/site-packages/opentelemetry/instrumentation/django/middleware.py", line 140, in process_request
    attributes = collect_request_attributes(environ)
  File "/home/omar/workspace/testapp/testapp/venv/lib/python3.8/site-packages/opentelemetry/instrumentation/wsgi/__init__.py", line 122, in collect_request_attributes
    result["http.url"] = wsgiref_util.request_uri(environ)
  File "/usr/lib/python3.8/wsgiref/util.py", line 72, in request_uri
    url = application_uri(environ)
  File "/usr/lib/python3.8/wsgiref/util.py", line 52, in application_uri
    url = environ['wsgi.url_scheme']+'://'
KeyError: 'wsgi.url_scheme'

thanks for your time
@oeltamasehy@cloudinn.net

**Comment by lonewolf3739** [comment]
Hi @OmarEltamasehy, Which version of `opentelemetry-instrumentation-django` are you using?

**Comment by adamantike** [comment]
Related to #280 and #334.
