### ISSUE TITLE
ElasticsearchInstrumentor support for elastic >= 8

### ISSUE THREAD

**Issue by daldoyle** [open-telemetry/opentelemetry-python-contrib#1881]
**Describe your environment** 
python 3.10
elasticsearch 8.8.0 (though tested all the way down to 8.0.0)
opentelemetry-instrumentation               0.39b0
opentelemetry-instrumentation-elasticsearch 0.39b0

**Steps to reproduce**

```
from opentelemetry.instrumentation.elasticsearch import ElasticsearchInstrumentor
ElasticsearchInstrumentor().instrument()
```

**What is the expected behavior?**

I expected it to work.

**What is the actual behavior?**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daldoyle/Code/venv/lib/python3.10/site-packages/opentelemetry/instrumentation/instrumentor.py", line 108, in instrument
    result = self._instrument(  # pylint: disable=assignment-from-no-return
  File "/Users/daldoyle/Code/venv/lib/python3.10/site-packages/opentelemetry/instrumentation/elasticsearch/__init__.py", line 140, in _instrument
    _wrap(
  File "/Users/daldoyle/Code/venv/lib/python3.10/site-packages/wrapt/wrappers.py", line 895, in wrap_function_wrapper
    return wrap_object(module, name, FunctionWrapper, (wrapper,))
  File "/Users/daldoyle/Code/venv/lib/python3.10/site-packages/wrapt/wrappers.py", line 841, in wrap_object
    (parent, attribute, original) = resolve_path(module, name)
  File "/Users/daldoyle/Code/venv/lib/python3.10/site-packages/wrapt/wrappers.py", line 829, in resolve_path
    original = lookup_attribute(parent, attribute)
  File "/Users/daldoyle/Code/venv/lib/python3.10/site-packages/wrapt/wrappers.py", line 827, in lookup_attribute
    return getattr(parent, attribute)
AttributeError: module 'elasticsearch' has no attribute 'Transport'
```

**Additional context**

It appears to work correctly if I drop down into the elasticsearch < 8 range, such as 7.0.0. I didn't dig too deep because we require > 8 in our environment.

There were a number of changes related to how Transport related items were handled in 8.0 so I'm guessing that this was one of them. It looks like this module is expecting there to be a `Transport.perform_request` which isn't there anymore.

I dug into the elasticapm module and it looks like they're doing the below to test for compatibility between versions. Sure enough, if I replace the code in this module with something similar it looks like it works. I haven't verified full functionality or edge cases but I thought I would mention here since it would be great to get this updated.

elasticapm -
```
    def get_instrument_list(self):
        try:
            import elastic_transport  # noqa: F401

            return [
                ("elastic_transport", "Transport.perform_request"),
            ]
        except ImportError:
            return [
                ("elasticsearch.transport", "Transport.perform_request"),
            ]
```

modified section of opentelemetry.instrumentation.elasticsearch
```
    def _instrument(self, **kwargs):
        """
        Instruments Elasticsearch module
        """
        tracer_provider = kwargs.get("tracer_provider")
        tracer = get_tracer(__name__, __version__, tracer_provider)
        request_hook = kwargs.get("request_hook")
        response_hook = kwargs.get("response_hook")
        _wrap(
            elastic_transport,
            "Transport.perform_request",
            _wrap_perform_request(
                tracer,
                self._span_name_prefix,
                request_hook,
                response_hook,
            ),
        )

    def _uninstrument(self, **kwargs):
        unwrap(elastic_transport.Transport, "perform_request")
```

**Comment by xrmx** [comment]
This should have been fixed in 6a40ffd90512e3e4636bddb20728f8f680b69f8a
