### ISSUE TITLE
aio-pika 9.1+ cannot be instrumented

### ISSUE THREAD

**Issue by akalex** [open-telemetry/opentelemetry-python-contrib#1978]
**Describe your environment** 
I caught up on this bug in the following environment:
Python 3.11.0
```
aio-pika==9.1.5
opentelemetry-api==1.20.0
opentelemetry-distro==0.41b0
opentelemetry-exporter-otlp==1.20.0
opentelemetry-exporter-otlp-proto-common==1.20.0
opentelemetry-exporter-otlp-proto-grpc==1.20.0
opentelemetry-exporter-otlp-proto-http==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aio-pika==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-instrumentation-fastapi==0.41b0
opentelemetry-instrumentation-grpc==0.41b0
opentelemetry-instrumentation-httpx==0.41b0
opentelemetry-instrumentation-requests==0.41b0
opentelemetry-propagator-b3==1.20.0
opentelemetry-proto==1.20.0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
```

**Steps to reproduce**
Please find an example of a simple consumer
```
import asyncio
import logging

import aio_pika

logging.basicConfig(level=logging.INFO)


async def main() -> None:
    connection = await aio_pika.connect_robust("amqp://guest:guest@127.0.0.1:5672/")

    queue_name = "test_queue"

    async with connection:
        # Creating channel
        channel = await connection.channel()
        # Declaring queue
        queue = await channel.declare_queue(queue_name, auto_delete=True)

        async with queue.iterator() as queue_iter:
            async for message in queue_iter:
                async with message.process():
                    print(message.body)

                    if queue.name in message.body.decode():
                        break
            await asyncio.sleep(0.1)


if __name__ == "__main__":
    logging.info("Starting RabbitMQ Consumer")
    asyncio.run(main())
    logging.info("RabbitMQ Consumer stopped")
```

To start the consumer, I used the command:
```
$ opentelemetry-instrument python3 -m rabbit_consumer
```

**What is the expected behavior?**
No error occurs and the trace information is collected and exported.

**What is the actual behavior?**
It fails with error `AttributeError: 'RobustChannel' object has no attribute 'connection'`

Please find full traceback below:
```
ERROR:asyncio:Exception in callback _task_done(<Task finishe...connection'")>) at /Users/akalex/venvs/ticket_hub/lib/python3.11/site-packages/aio_pika/tools.py:43
handle: <Handle _task_done(<Task finishe...connection'")>) at /Users/akalex/venvs/ticket_hub/lib/python3.11/site-packages/aio_pika/tools.py:43>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/akalex/venvs/ticket_hub/lib/python3.11/site-packages/aio_pika/tools.py", line 47, in _task_done
    raise exc
  File "/Users/akalex/venvs/ticket_hub/lib/python3.11/site-packages/opentelemetry/instrumentation/aio_pika/callback_decorator.py", line 51, in decorated
    span = self._get_span(message)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akalex/venvs/ticket_hub/lib/python3.11/site-packages/opentelemetry/instrumentation/aio_pika/callback_decorator.py", line 38, in _get_span
    builder.set_channel(self._queue.channel)
  File "/Users/akalex/venvs/ticket_hub/lib/python3.11/site-packages/opentelemetry/instrumentation/aio_pika/span_builder.py", line 52, in set_channel
    connection = channel.connection
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'RobustChannel' object has no attribute 'connection'
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-15' coro=<consumer() done, defined at /Users/akalex/venvs/ticket_hub/lib/python3.11/site-packages/aio_pika/queue.py:31> exception=AttributeError("'RobustChannel' object has no attribute 'connection'")>
Traceback (most recent call last):
  File "/Users/akalex/venvs/ticket_hub/lib/python3.11/site-packages/aio_pika/queue.py", line 37, in consumer
    return await create_task(callback, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akalex/venvs/ticket_hub/lib/python3.11/site-packages/opentelemetry/instrumentation/aio_pika/callback_decorator.py", line 51, in decorated
    span = self._get_span(message)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akalex/venvs/ticket_hub/lib/python3.11/site-packages/opentelemetry/instrumentation/aio_pika/callback_decorator.py", line 38, in _get_span
    builder.set_channel(self._queue.channel)
  File "/Users/akalex/venvs/ticket_hub/lib/python3.11/site-packages/opentelemetry/instrumentation/aio_pika/span_builder.py", line 52, in set_channel
    connection = channel.connection
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'RobustChannel' object has no attribute 'connection'

```

**Additional context**
-

**Comment by akalex** [comment]
There is an open [feature-request](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1835), so closing this out.
