### ISSUE TITLE
opentelemetry-instrument can't run flask app

### ISSUE THREAD

**Issue by ymotongpoo** [open-telemetry/opentelemetry-python-contrib#2004]
**Describe your environment** 

I installed my home Python from the following Homebrew version:

```
$ brew --version
Homebrew 4.1.16
Homebrew/homebrew-core (git revision 6c73dd46155; last commit 2023-10-01)
Homebrew/homebrew-cask (git revision 81801675fc; last commit 2023-10-01)
```

And I used the following Python to create a venv environment:

```
$ python3.12 -V
Python 3.12.0
```

I create a venv and upgraded the pip init:

```
$ python3.12 -m venv .venv
$ .venv/bin/pip install --upgrade pip
Requirement already satisfied: pip in ./.venv/lib/python3.12/site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/e0/63/b428aaca15fcd98c39b07ca7149e24bc14205ad0f1c80ba2b01835aedde1/pip-23.3-py3-none-any.whl.metadata
  Downloading pip-23.3-py3-none-any.whl.metadata (3.5 kB)
Using cached pip-23.3-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Successfully installed pip-23.3
```

**Steps to reproduce**

1. Started following the sample on [this document](https://opentelemetry.io/docs/instrumentation/python/getting-started/) and created a small flask app.

```py
from random import randint
from flask import Flask

app = Flask(__name__)

@app.route("/rolldice")
def roll_dice():
    return str(roll())

def roll():
    return randint(1, 6)
```

2. Then I installed `flask < 3` as dependency and `opentelemetry-distro` for auto instrumentation:

```console
$ .venv/bin/pip install "flask<3"
Collecting flask<3
  Obtaining dependency information for flask<3 from https://files.pythonhosted.org/packages/fd/56/26f0be8adc2b4257df20c1c4260ddd0aa396cf8e75d90ab2f7ff99bc34f9/flask-2.3.3-py3-none-any.whl.metadata
  Downloading flask-2.3.3-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: Werkzeug>=2.3.7 in ./.venv/lib/python3.12/site-packages (from flask<3) (3.0.0)
Requirement already satisfied: Jinja2>=3.1.2 in ./.venv/lib/python3.12/site-packages (from flask<3) (3.1.2)
Requirement already satisfied: itsdangerous>=2.1.2 in ./.venv/lib/python3.12/site-packages (from flask<3) (2.1.2)
Requirement already satisfied: click>=8.1.3 in ./.venv/lib/python3.12/site-packages (from flask<3) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in ./.venv/lib/python3.12/site-packages (from flask<3) (1.6.3)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.12/site-packages (from Jinja2>=3.1.2->flask<3) (2.1.3)
Using cached flask-2.3.3-py3-none-any.whl (96 kB)
Installing collected packages: flask
Successfully installed flask-2.3.3

$ .venv/bin/pip install opentelemetry-distro
Collecting opentelemetry-distro
  Downloading opentelemetry_distro-0.41b0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-api~=1.12 (from opentelemetry-distro)
  Downloading opentelemetry_api-1.20.0-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-instrumentation==0.41b0 (from opentelemetry-distro)
  Downloading opentelemetry_instrumentation-0.41b0-py3-none-any.whl.metadata (5.9 kB)
Collecting opentelemetry-sdk~=1.13 (from opentelemetry-distro)
  Downloading opentelemetry_sdk-1.20.0-py3-none-any.whl.metadata (1.5 kB)
Collecting setuptools>=16.0 (from opentelemetry-instrumentation==0.41b0->opentelemetry-distro)
  Downloading setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
Collecting wrapt<2.0.0,>=1.0.0 (from opentelemetry-instrumentation==0.41b0->opentelemetry-distro)
  Downloading wrapt-1.15.0-py3-none-any.whl (22 kB)
Collecting deprecated>=1.2.6 (from opentelemetry-api~=1.12->opentelemetry-distro)
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting importlib-metadata<7.0,>=6.0 (from opentelemetry-api~=1.12->opentelemetry-distro)
  Downloading importlib_metadata-6.8.0-py3-none-any.whl.metadata (5.1 kB)
Collecting opentelemetry-semantic-conventions==0.41b0 (from opentelemetry-sdk~=1.13->opentelemetry-distro)
  Downloading opentelemetry_semantic_conventions-0.41b0-py3-none-any.whl.metadata (2.3 kB)
Collecting typing-extensions>=3.7.4 (from opentelemetry-sdk~=1.13->opentelemetry-distro)
  Downloading typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting zipp>=0.5 (from importlib-metadata<7.0,>=6.0->opentelemetry-api~=1.12->opentelemetry-distro)
  Downloading zipp-3.17.0-py3-none-any.whl.metadata (3.7 kB)
Downloading opentelemetry_distro-0.41b0-py3-none-any.whl (3.3 kB)
Downloading opentelemetry_instrumentation-0.41b0-py3-none-any.whl (25 kB)
Downloading opentelemetry_api-1.20.0-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 6.2 MB/s eta 0:00:00
Downloading opentelemetry_sdk-1.20.0-py3-none-any.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.9/103.9 kB 11.2 MB/s eta 0:00:00
Downloading opentelemetry_semantic_conventions-0.41b0-py3-none-any.whl (26 kB)
Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Downloading importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Downloading setuptools-68.2.2-py3-none-any.whl (807 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 20.7 MB/s eta 0:00:00
Downloading typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Downloading zipp-3.17.0-py3-none-any.whl (7.4 kB)
Installing collected packages: zipp, wrapt, typing-extensions, setuptools, opentelemetry-semantic-conventions, importlib-metadata, deprecated, opentelemetry-api, opentelemetry-sdk, opentelemetry-instrumentation, opentelemetry-distro
Successfully installed deprecated-1.2.14 importlib-metadata-6.8.0 opentelemetry-api-1.20.0 opentelemetry-distro-0.41b0 opentelemetry-instrumentation-0.41b0 opentelemetry-sdk-1.20.0 opentelemetry-semantic-conventions-0.41b0 setuptools-68.2.2 typing-extensions-4.8.0 wrapt-1.15.0 zipp-3.17.0
```

3. After that, I ran `opentelemtry-bootstrap install` for the app:

```console
$ .venv/bin/opentelemetry-bootstrap -a install
Collecting opentelemetry-instrumentation-aws-lambda==0.41b0
  Downloading opentelemetry_instrumentation_aws_lambda-0.41b0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: opentelemetry-instrumentation==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-aws-lambda==0.41b0) (0.41b0)
Collecting opentelemetry-propagator-aws-xray==1.0.1 (from opentelemetry-instrumentation-aws-lambda==0.41b0)
  Downloading opentelemetry_propagator_aws_xray-1.0.1-py3-none-any.whl (10 kB)
Requirement already satisfied: opentelemetry-semantic-conventions==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-aws-lambda==0.41b0) (0.41b0)
Requirement already satisfied: opentelemetry-api~=1.4 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-aws-lambda==0.41b0) (1.20.0)
Requirement already satisfied: setuptools>=16.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-aws-lambda==0.41b0) (68.2.2)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-aws-lambda==0.41b0) (1.15.0)
Requirement already satisfied: deprecated>=1.2.6 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.4->opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-aws-lambda==0.41b0) (1.2.14)
Requirement already satisfied: importlib-metadata<7.0,>=6.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.4->opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-aws-lambda==0.41b0) (6.8.0)
Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.12/site-packages (from importlib-metadata<7.0,>=6.0->opentelemetry-api~=1.4->opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-aws-lambda==0.41b0) (3.17.0)
Downloading opentelemetry_instrumentation_aws_lambda-0.41b0-py3-none-any.whl (11 kB)
Installing collected packages: opentelemetry-propagator-aws-xray, opentelemetry-instrumentation-aws-lambda
Successfully installed opentelemetry-instrumentation-aws-lambda-0.41b0 opentelemetry-propagator-aws-xray-1.0.1
Collecting opentelemetry-instrumentation-dbapi==0.41b0
  Downloading opentelemetry_instrumentation_dbapi-0.41b0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: opentelemetry-api~=1.12 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-dbapi==0.41b0) (1.20.0)
Requirement already satisfied: opentelemetry-instrumentation==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-dbapi==0.41b0) (0.41b0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-dbapi==0.41b0) (0.41b0)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-dbapi==0.41b0) (1.15.0)
Requirement already satisfied: setuptools>=16.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-dbapi==0.41b0) (68.2.2)
Requirement already satisfied: deprecated>=1.2.6 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-dbapi==0.41b0) (1.2.14)
Requirement already satisfied: importlib-metadata<7.0,>=6.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-dbapi==0.41b0) (6.8.0)
Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.12/site-packages (from importlib-metadata<7.0,>=6.0->opentelemetry-api~=1.12->opentelemetry-instrumentation-dbapi==0.41b0) (3.17.0)
Downloading opentelemetry_instrumentation_dbapi-0.41b0-py3-none-any.whl (10 kB)
Installing collected packages: opentelemetry-instrumentation-dbapi
Successfully installed opentelemetry-instrumentation-dbapi-0.41b0
Collecting opentelemetry-instrumentation-logging==0.41b0
  Downloading opentelemetry_instrumentation_logging-0.41b0-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: opentelemetry-api~=1.12 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-logging==0.41b0) (1.20.0)
Requirement already satisfied: opentelemetry-instrumentation==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-logging==0.41b0) (0.41b0)
Requirement already satisfied: setuptools>=16.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-logging==0.41b0) (68.2.2)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-logging==0.41b0) (1.15.0)
Requirement already satisfied: deprecated>=1.2.6 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-logging==0.41b0) (1.2.14)
Requirement already satisfied: importlib-metadata<7.0,>=6.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-logging==0.41b0) (6.8.0)
Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.12/site-packages (from importlib-metadata<7.0,>=6.0->opentelemetry-api~=1.12->opentelemetry-instrumentation-logging==0.41b0) (3.17.0)
Downloading opentelemetry_instrumentation_logging-0.41b0-py2.py3-none-any.whl (12 kB)
Installing collected packages: opentelemetry-instrumentation-logging
Successfully installed opentelemetry-instrumentation-logging-0.41b0
Collecting opentelemetry-instrumentation-sqlite3==0.41b0
  Downloading opentelemetry_instrumentation_sqlite3-0.41b0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: opentelemetry-api~=1.12 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-sqlite3==0.41b0) (1.20.0)
Requirement already satisfied: opentelemetry-instrumentation-dbapi==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-sqlite3==0.41b0) (0.41b0)
Requirement already satisfied: opentelemetry-instrumentation==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-sqlite3==0.41b0) (0.41b0)
Requirement already satisfied: setuptools>=16.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-sqlite3==0.41b0) (68.2.2)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-sqlite3==0.41b0) (1.15.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-dbapi==0.41b0->opentelemetry-instrumentation-sqlite3==0.41b0) (0.41b0)
Requirement already satisfied: deprecated>=1.2.6 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-sqlite3==0.41b0) (1.2.14)
Requirement already satisfied: importlib-metadata<7.0,>=6.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-sqlite3==0.41b0) (6.8.0)
Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.12/site-packages (from importlib-metadata<7.0,>=6.0->opentelemetry-api~=1.12->opentelemetry-instrumentation-sqlite3==0.41b0) (3.17.0)
Downloading opentelemetry_instrumentation_sqlite3-0.41b0-py3-none-any.whl (8.7 kB)
Installing collected packages: opentelemetry-instrumentation-sqlite3
Successfully installed opentelemetry-instrumentation-sqlite3-0.41b0
Collecting opentelemetry-instrumentation-urllib==0.41b0
  Downloading opentelemetry_instrumentation_urllib-0.41b0-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: opentelemetry-api~=1.12 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-urllib==0.41b0) (1.20.0)
Requirement already satisfied: opentelemetry-instrumentation==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-urllib==0.41b0) (0.41b0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-urllib==0.41b0) (0.41b0)
Collecting opentelemetry-util-http==0.41b0 (from opentelemetry-instrumentation-urllib==0.41b0)
  Downloading opentelemetry_util_http-0.41b0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: setuptools>=16.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-urllib==0.41b0) (68.2.2)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-urllib==0.41b0) (1.15.0)
Requirement already satisfied: deprecated>=1.2.6 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-urllib==0.41b0) (1.2.14)
Requirement already satisfied: importlib-metadata<7.0,>=6.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-urllib==0.41b0) (6.8.0)
Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.12/site-packages (from importlib-metadata<7.0,>=6.0->opentelemetry-api~=1.12->opentelemetry-instrumentation-urllib==0.41b0) (3.17.0)
Downloading opentelemetry_instrumentation_urllib-0.41b0-py3-none-any.whl (11 kB)
Downloading opentelemetry_util_http-0.41b0-py3-none-any.whl (6.9 kB)
Installing collected packages: opentelemetry-util-http, opentelemetry-instrumentation-urllib
Successfully installed opentelemetry-instrumentation-urllib-0.41b0 opentelemetry-util-http-0.41b0
Collecting opentelemetry-instrumentation-wsgi==0.41b0
  Downloading opentelemetry_instrumentation_wsgi-0.41b0-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: opentelemetry-api~=1.12 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-wsgi==0.41b0) (1.20.0)
Requirement already satisfied: opentelemetry-instrumentation==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-wsgi==0.41b0) (0.41b0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-wsgi==0.41b0) (0.41b0)
Requirement already satisfied: opentelemetry-util-http==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-wsgi==0.41b0) (0.41b0)
Requirement already satisfied: setuptools>=16.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-wsgi==0.41b0) (68.2.2)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-wsgi==0.41b0) (1.15.0)
Requirement already satisfied: deprecated>=1.2.6 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-wsgi==0.41b0) (1.2.14)
Requirement already satisfied: importlib-metadata<7.0,>=6.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-wsgi==0.41b0) (6.8.0)
Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.12/site-packages (from importlib-metadata<7.0,>=6.0->opentelemetry-api~=1.12->opentelemetry-instrumentation-wsgi==0.41b0) (3.17.0)
Downloading opentelemetry_instrumentation_wsgi-0.41b0-py3-none-any.whl (13 kB)
Installing collected packages: opentelemetry-instrumentation-wsgi
Successfully installed opentelemetry-instrumentation-wsgi-0.41b0
Collecting opentelemetry-instrumentation-flask==0.41b0
  Downloading opentelemetry_instrumentation_flask-0.41b0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: opentelemetry-api~=1.12 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-flask==0.41b0) (1.20.0)
Requirement already satisfied: opentelemetry-instrumentation-wsgi==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-flask==0.41b0) (0.41b0)
Requirement already satisfied: opentelemetry-instrumentation==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-flask==0.41b0) (0.41b0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-flask==0.41b0) (0.41b0)
Requirement already satisfied: opentelemetry-util-http==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-flask==0.41b0) (0.41b0)
Collecting packaging>=21.0 (from opentelemetry-instrumentation-flask==0.41b0)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: setuptools>=16.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-flask==0.41b0) (68.2.2)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-flask==0.41b0) (1.15.0)
Requirement already satisfied: deprecated>=1.2.6 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-flask==0.41b0) (1.2.14)
Requirement already satisfied: importlib-metadata<7.0,>=6.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-flask==0.41b0) (6.8.0)
Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.12/site-packages (from importlib-metadata<7.0,>=6.0->opentelemetry-api~=1.12->opentelemetry-instrumentation-flask==0.41b0) (3.17.0)
Downloading opentelemetry_instrumentation_flask-0.41b0-py3-none-any.whl (13 kB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Installing collected packages: packaging, opentelemetry-instrumentation-flask
Successfully installed opentelemetry-instrumentation-flask-0.41b0 packaging-23.2
Collecting opentelemetry-instrumentation-jinja2==0.41b0
  Downloading opentelemetry_instrumentation_jinja2-0.41b0-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: opentelemetry-api~=1.12 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-jinja2==0.41b0) (1.20.0)
Requirement already satisfied: opentelemetry-instrumentation==0.41b0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-jinja2==0.41b0) (0.41b0)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation-jinja2==0.41b0) (1.15.0)
Requirement already satisfied: setuptools>=16.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-instrumentation==0.41b0->opentelemetry-instrumentation-jinja2==0.41b0) (68.2.2)
Requirement already satisfied: deprecated>=1.2.6 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-jinja2==0.41b0) (1.2.14)
Requirement already satisfied: importlib-metadata<7.0,>=6.0 in ./.venv/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-jinja2==0.41b0) (6.8.0)
Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.12/site-packages (from importlib-metadata<7.0,>=6.0->opentelemetry-api~=1.12->opentelemetry-instrumentation-jinja2==0.41b0) (3.17.0)
Downloading opentelemetry_instrumentation_jinja2-0.41b0-py2.py3-none-any.whl (9.0 kB)
Installing collected packages: opentelemetry-instrumentation-jinja2
Successfully installed opentelemetry-instrumentation-jinja2-0.41b0
```

4. Now the time to run `opentelemetry-instrument`:

```console
$ .venv/bin/opentelemetry-instrument --traces_exporter console --metrics_exporter console flask run -p 8080
```

**What is the expected behavior?**

I see the logs from flask that is running with 8080 port and see trace and metrics JSON output on the console after that.

**What is the actual behavior?**

The following stack trace saying `__init__.py` has some issues on `execl()` call.

```
.venv/bin/opentelemetry-instrument --traces_exporter console --metrics_exporter console flask run -p 8080
Traceback (most recent call last):
  File "/Users/yoshifumi/personal/devrel-demos/devops/otel-run-flask/.venv/bin/opentelemetry-instrument", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/yoshifumi/personal/devrel-demos/devops/otel-run-flask/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/auto_instrumentation/__init__.py", line 115, in run
    execl(executable, executable, *args.command_args)
  File "<frozen os>", line 548, in execl
TypeError: execv: path should be string, bytes or os.PathLike, not NoneType
```

**Additional context**
N/A

**Comment by ymotongpoo** [comment]
Though I just took a glance of the code of `opentelemtery-instrument`, the line mentioned in the stack trace says, it has something to do with the call of `execl`.

[The exact line](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/3478831838ce54a972f7434ae6098f9bb28dc494/opentelemetry-instrumentation/src/opentelemetry/instrumentation/auto_instrumentation/__init__.py#L115) is like this:

```py
    executable = which(args.command)
    execl(executable, executable, *args.command_args)
```

However according to [the official doc of `os` module](https://docs.python.org/3/library/os.html#os.execl), the arguments of the `execl` function should receive arguments to the first argument of the `execl` function, like:

```py
os.execl(path, arg0, arg1, ...)
```

It seems the second argument `executable` in the line to be incorrect.

**Comment by aabmass** [comment]
After reading around a bit, I believe `arg0` is intended to be the filename for the process. It's supposed to behave like the underlying [`execl()` in C](https://linux.die.net/man/3/execl#:~:text=the%20executed%20program.-,The%20first%20argument%2C%20by%20convention%2C%20should%20point%20to%20the%20filename%20associated%20with%20the%20file%20being%20executed.,-The%20list%20of):

> The first argument, by convention, should point to the filename associated with the file being executed.

Maybe we could add a comment to the source code as I remember being confused by this before.

For your actual error:

> ```
> TypeError: execv: path should be string, bytes or os.PathLike, not NoneType
> ```

I think `which(args.command)` is not finding the `flask` executable and returns `None`. It looks like it's in a virtualenv which is not in your PATH. Try either an absolute or relative path to `flask` or sourcing the virtualenv first.

**Comment by aabmass** [comment]
A few other things to note:
- We aren't testing with Python 3.12 yet https://github.com/open-telemetry/opentelemetry-python/issues/3370
- `flask < 3` is installing Werkzeug `3.0` from your pip logs because flask doesn't set an upper bound https://github.com/pallets/flask/discussions/5290. This probably will fail when you run it, regardless of OTel.

**Comment by ymotongpoo** [comment]
Thank you, @aabmass. I missed that the path for flask is wrong. I hoped the error message is friendlier tho. Anyway, it was my problem. Thank you for taking a time for the investigation. Close the issue.
