### ISSUE TITLE
Celery instrumentation doesn't import after a clean install

### ISSUE THREAD

**Issue by bartosz-banachewicz-asi** [open-telemetry/opentelemetry-python-contrib#2071]
**Describe your environment**
Python 3.11 on mac, but doesn't work on other platforms too.

**Steps to reproduce**
```
pip3 install opentelemetry-instrumentation-celery
```
then try to import:

```
Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from opentelemetry.instrumentation.celery import CeleryInstrumentor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bartek/repos/venv/lib/python3.11/site-packages/opentelemetry/instrumentation/celery/__init__.py", line 66, in <module>
    from billiard.einfo import ExceptionInfo
ModuleNotFoundError: No module named 'billiard'
```

**What is the expected behavior?**
`CeleryInstrumentor` importing properly.

**What is the actual behavior?**
The package is installed properly:
```
Package                              Version
------------------------------------ -------
Deprecated                           1.2.14
importlib-metadata                   6.8.0
opentelemetry-api                    1.21.0
opentelemetry-instrumentation        0.42b0
opentelemetry-instrumentation-celery 0.42b0
opentelemetry-semantic-conventions   0.42b0
pip                                  23.2.1
setuptools                           68.1.2
wrapt                                1.16.0
zipp                                 3.17.0
```
The import fails.

**Comment by bartosz-banachewicz-asi** [comment]
Ah, I think I see the issue; it needs actual celery as dependencies.
