### ISSUE TITLE
`Psycopg2Instrumentor().instrument_connection` raises `AttributeError: 'psycopg2.extensions.connection' object has no attribute '_is_instrumented_by_opentelemetry'`

### ISSUE THREAD

**Issue by alexmojaki** [open-telemetry/opentelemetry-python-contrib#2522]
**Describe your environment**

```
opentelemetry-instrumentation-psycopg2==0.45b0
psycopg2-binary==2.9.9
```

**Steps to reproduce**

Use `Psycopg2Instrumentor().instrument_connection`. For example:

```python
import psycopg2
from opentelemetry.instrumentation.psycopg2 import Psycopg2Instrumentor

connection = psycopg2.connect(database='database', user='user', password='secret', host='0.0.0.0', port=5432)

Psycopg2Instrumentor().instrument_connection(connection)
```

and run a database with:

```
docker run --name postgres \
    -e POSTGRES_USER=user \
    -e POSTGRES_PASSWORD=secret \
    -e POSTGRES_DB=database \
    -p 5432:5432 -d postgres
```

**What is the actual behavior?**

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    Psycopg2Instrumentor().instrument_connection(connection)
  File "/home/alex/work/logfire/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/psycopg2/__init__.py", line 164, in instrument_connection
    connection._is_instrumented_by_opentelemetry = False
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute '_is_instrumented_by_opentelemetry'
```

**Additional context**

Here's where the error happens:

https://github.com/open-telemetry/opentelemetry-python-contrib/blob/46d2ce6acea9a1a6cb1a4d4c863077002f5f7d21/instrumentation/opentelemetry-instrumentation-psycopg2/src/opentelemetry/instrumentation/psycopg2/__init__.py#L164

The code seems tested here:

https://github.com/open-telemetry/opentelemetry-python-contrib/blob/46d2ce6acea9a1a6cb1a4d4c863077002f5f7d21/instrumentation/opentelemetry-instrumentation-psycopg2/tests/test_psycopg2_integration.py#L210

but it doesn't get the error because it's a mock connection.

**Comment by xrmx** [comment]
@alexmojaki would be great if you can open a PR

**Comment by qiuge615** [comment]
@xrmx regarding this issue, shall I reference mysql/sqlite3 to fix this issue? Tested this approach locally, the instrument works and the trace can be displayed.
Shall I create another issue to add the two parameters _otel_orig_cursor_factory and _is_instrumented_by_opentelemetry in connection object? The same approach may applies for psycopg.

**Comment by xrmx** [comment]
@qiuge615 If you have already some code open a PR so we can discuss looking at it :) Thanks!

**Comment by qiuge615** [comment]
@xrmx Appreciate your quick reply, I will create a PR with the changes, thank you!

**Comment by qiuge615** [comment]
@xrmx Created PR with the fix, please review, thanks.

**Comment by tammy-baylis-swi** [comment]
I've also created a PR. Please see its OP for rationale: https://github.com/open-telemetry/opentelemetry-python-contrib/pull/3043 Please let me know what you think! I'm fine with whichever approach.
