### ISSUE TITLE
Bazelisk build failed

### ISSUE THREAD

**Issue by pjachowi** [open-telemetry/opentelemetry-python-contrib#2762]
### Describe your environment

OS: Ubuntu
Python version: Python 3.9.19
Package version: 0.47b0

### What happened?

Attempt to build a Python project using opentelemetry.instrumentation.grpc using Bazel fails.
Here is the minimal project reproducing the problem: https://github.com/pjachowi/otel_intrumentation_problem

### Steps to Reproduce

1. Clone the repo https://github.com/pjachowi/otel_intrumentation_problem
2. bazelisk run //:requirements.update
3. bazelisk run //:test

### Expected Result

Successful run

### Actual Result

$ bazelisk run //:test
INFO: Analyzed target //:test (73 packages loaded, 4272 targets configured).
INFO: Found 1 target...
Target //:test up-to-date:
  bazel-bin/test
INFO: Elapsed time: 0.401s, Critical Path: 0.04s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/test
Traceback (most recent call last):
  File "/home/nobody/.cache/bazel/_bazel_nobody/b0c935cccbea1e51f1a6303d0c0ad81d/execroot/__main__/bazel-out/k8-fastbuild/bin/test.runfiles/__main__/test.py", line 1, in <module>
    from opentelemetry.instrumentation import grpc
  File "/home/nobody/.cache/bazel/_bazel_nobody/b0c935cccbea1e51f1a6303d0c0ad81d/execroot/__main__/bazel-out/k8-fastbuild/bin/test.runfiles/py_deps_opentelemetry_instrumentation_grpc/site-packages/opentelemetry/instrumentation/grpc/__init__.py", line 291, in <module>
    from opentelemetry.instrumentation.instrumentor import BaseInstrumentor
  File "/home/nobody/.cache/bazel/_bazel_nobody/b0c935cccbea1e51f1a6303d0c0ad81d/execroot/__main__/bazel-out/k8-fastbuild/bin/test.runfiles/py_deps_opentelemetry_instrumentation/site-packages/opentelemetry/instrumentation/instrumentor.py", line 27, in <module>
    from opentelemetry.instrumentation.dependencies import (
  File "/home/nobody/.cache/bazel/_bazel_nobody/b0c935cccbea1e51f1a6303d0c0ad81d/execroot/__main__/bazel-out/k8-fastbuild/bin/test.runfiles/py_deps_opentelemetry_instrumentation/site-packages/opentelemetry/instrumentation/dependencies.py", line 4, in <module>
    from pkg_resources import (
  File "/home/nobody/.cache/bazel/_bazel_nobody/b0c935cccbea1e51f1a6303d0c0ad81d/execroot/__main__/bazel-out/k8-fastbuild/bin/test.runfiles/py_deps_setuptools/site-packages/pkg_resources/__init__.py", line 96, in <module>
    from jaraco.text import (
  File "/home/nobody/.cache/bazel/_bazel_nobody/b0c935cccbea1e51f1a6303d0c0ad81d/execroot/__main__/bazel-out/k8-fastbuild/bin/test.runfiles/py_deps_setuptools/site-packages/setuptools/_vendor/jaraco/text/__init__.py", line 231, in <module>
    files(__name__).joinpath('Lorem ipsum.txt').read_text(encoding='utf-8')
  File "/home/nobody/.cache/bazel/_bazel_nobody/b0c935cccbea1e51f1a6303d0c0ad81d/external/python3_9_x86_64-unknown-linux-gnu/lib/python3.9/pathlib.py", line 1266, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/home/nobody/.cache/bazel/_bazel_nobody/b0c935cccbea1e51f1a6303d0c0ad81d/external/python3_9_x86_64-unknown-linux-gnu/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/home/nobody/.cache/bazel/_bazel_nobody/b0c935cccbea1e51f1a6303d0c0ad81d/external/python3_9_x86_64-unknown-linux-gnu/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nobody/.cache/bazel/_bazel_nobody/b0c935cccbea1e51f1a6303d0c0ad81d/execroot/__main__/bazel-out/k8-fastbuild/bin/test.runfiles/py_deps_setuptools/site-packages/setuptools/_vendor/jaraco/text/Lorem ipsum.txt'

### Additional context

The problem appared with the latest release 0.47b0, however pinning `opentelemetry-instrumentation-grpc==0.46b0` reproduces the problem as well.

### Would you like to implement a fix?

None

**Comment by xrmx** [comment]
From the stacktrace this looks unrelated though, looks more like the tool is messing with some unrelated stuff in setuptools.

**Comment by pjachowi** [comment]
> I have the same issue - you can use can see how I fixed my example app [grafana/docker-otel-lgtm#81](https://github.com/grafana/docker-otel-lgtm/pull/81)

I managed to fix the problem by adding to requirements.in
```
setuptools==70.3.0
```

**Comment by ocelotl** [comment]
I asked Claude to review this issue and Claude suggests it be closed with this explanation:

> Bazel/setuptools 70 tooling incompatibility, not a contrib code issue.
>
> Proof in `main`: — (external tooling incompatibility)

To guard against a mistaken suggestion, Claude then independently re-verified this conclusion:

> Verified: this is a Bazel/setuptools 70 tooling incompatibility, not a contrib code issue (contrib already migrated off `pkg_resources`).

Claude evaluated this issue with high confidence that it can be closed.

Claude has classified this issue as out of scope (it belongs in core, is a policy decision, or was explicitly declined).

The intention of this comment is to make it easier for a human being to review this issue before making a decision.
