### ISSUE TITLE
Test failure in opentelemetry-instrumentation-aiohttp-client with yarl 1.13

### ISSUE THREAD

**Issue by musicinmybrain** [open-telemetry/opentelemetry-python-contrib#2916]
### Describe your environment

OS: Fedora 42/Rawhide (development version)
Python version: 3.13.0 (or 3.12.6)
Package version: 1.27.0 (or current `main`, e4ece57a8136310ed379c04fa77c6b6f8d009bbc)

### What happened?

I know that you currently have `yarl` pinned to `yarl==1.9.4` for testing, but [in Fedora](https://src.fedoraproject.org/rpms/python-opentelemetry-contrib) we use the system versions of all dependencies. While yarl is at 1.9.4 in stable releases, Rawhide is now at `yarl` 1.13.1. A regression appeared in the tests for `opentelemetry-instrumentation-aiohttp-client` between `yarl` 1.12.1 and `yarl` 1.13.1.

### Steps to Reproduce

To reproduce this in a virtualenv, I ran the tests manually, which is a bit messy, but the below steps work. I had to unpin `zipp` to fix a dependency conflict. I started with a “control” run:

```
$ gh repo clone open-telemetry/opentelemetry-python
$ gh repo clone open-telemetry/opentelemetry-python-contrib
$ cd opentelemetry-python-contrib
$ python3.12 -m venv _e
$ . _e/bin/activate
(_e) $ pip install ../opentelemetry-python/opentelemetry-api/
(_e) $ pip install ../opentelemetry-python/opentelemetry-semantic-conventions/
(_e) $ pip install ./opentelemetry-instrumentation/
(_e) $ pip install ./util/opentelemetry-util-http/
(_e) $ cd ./instrumentation/opentelemetry-instrumentation-aiohttp-client/
(_e) $ pip install -e .
(_e) $ pip install -r <(sed -r -e '/^-e /d' -e 's/(zipp)==/\1>=/' test-requirements.txt)
(_e) $ pip install ../../../opentelemetry-python/opentelemetry-sdk/
(_e) $ pip install ../../../opentelemetry-python/tests/opentelemetry-test-utils/
(_e) $ python -m pytest
```

(All tests passed.)

Now, updating `yarl`:

```
(_e) $ pip install --upgrade yarl==1.13.1
(_e) $ python -m pytest
```

Now `TestAioHttpIntegration.test_too_many_redirects` fails, with details in the “Actual Result” section.

Finally, upgrading `yarl` even further just to see what happens:

```
(_e) $ pip install --upgrade yarl
[…]
Installing collected packages: yarl
  Attempting uninstall: yarl
    Found existing installation: yarl 1.13.1
    Uninstalling yarl-1.13.1:
      Successfully uninstalled yarl-1.13.1
Successfully installed yarl-1.15.5
(_e) $ python -m pytest
```

This reproduces the same regression seen with `yarl` 1.13.1.

### Expected Result

```
========================================= 33 passed, 4 warnings in 5.50s =========================================
```

### Actual Result

```
==================================================== FAILURES ====================================================
_________________________________ TestAioHttpIntegration.test_too_many_redirects _________________________________

self = <tests.test_aiohttp_client_integration.TestAioHttpIntegration testMethod=test_too_many_redirects>

    def test_too_many_redirects(self):
        async def request_handler(request):
            # Create a redirect loop.
            location = request.url
            assert "traceparent" in request.headers
            raise aiohttp.web.HTTPFound(location=location)

        host, port = self._http_request(
            trace_config=aiohttp_client.create_trace_config(),
            url="/test_too_many_redirects",
            request_handler=request_handler,
            max_redirects=2,
        )

>       self.assert_spans(
            [   
                (   
                    "GET",
                    (StatusCode.ERROR, "TooManyRedirects"),
                    {   
                        SpanAttributes.HTTP_METHOD: "GET",
                        SpanAttributes.HTTP_URL: f"http://{host}:{port}/test_too_many_redirects",
                    },
                )
            ]
        )

tests/test_aiohttp_client_integration.py:494:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_aiohttp_client_integration.py:91: in assert_spans
    self.assertEqual(
E   AssertionError: Lists differ: [('GE[23 chars] 2>, None), {'http.method': 'GET', 'http.url':[72 chars]00})] != [('GE[23 chars] 2>, 'TooManyRedirects'), {'http.method': 'GET[61 chars]s'})]
E   
E   First differing element 0:
E   ('GET[22 chars] 2>, None), {'http.method': 'GET', 'http.url':[71 chars]500})
E   ('GET[22 chars] 2>, 'TooManyRedirects'), {'http.method': 'GET[60 chars]ts'})
E   
E     [('GET',
E   -   (<StatusCode.ERROR: 2>, None),
E   ?                           ^
E   
E   +   (<StatusCode.ERROR: 2>, 'TooManyRedirects'),
E   ?                           ^^ +++ ++ ++++++++
E   
E       {'http.method': 'GET',
E   -    'http.status_code': 500,
E        'http.url': 'http://127.0.0.1:33779/test_too_many_redirects'})]
----------------------------------------------- Captured log call ------------------------------------------------
ERROR    aiohttp.server:web_protocol.py:428 Error handling request
Traceback (most recent call last):
  File "/home/ben/src/forks/opentelemetry-python-contrib/_e/lib64/python3.12/site-packages/aiohttp/web_protocol.py", line 459, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/src/forks/opentelemetry-python-contrib/_e/lib64/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/src/forks/opentelemetry-python-contrib/instrumentation/opentelemetry-instrumentation-aiohttp-client/tests/test_aiohttp_client_integration.py", line 483, in request_handler
    location = request.url
               ^^^^^^^^^^^
  File "aiohttp/_helpers.pyx", line 26, in aiohttp._helpers.reify.__get__
  File "/home/ben/src/forks/opentelemetry-python-contrib/_e/lib64/python3.12/site-packages/aiohttp/web_request.py", line 453, in url
    url = URL.build(scheme=self.scheme, host=self.host)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/src/forks/opentelemetry-python-contrib/_e/lib64/python3.12/site-packages/yarl/_url.py", line 385, in build
    netloc = cls._make_netloc(
             ^^^^^^^^^^^^^^^^^
  File "/home/ben/src/forks/opentelemetry-python-contrib/_e/lib64/python3.12/site-packages/yarl/_url.py", line 1057, in _make_netloc
    ret = cls._encode_host(host)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/src/forks/opentelemetry-python-contrib/_e/lib64/python3.12/site-packages/yarl/_url.py", line 1038, in _encode_host
    _host_validate(host)
  File "/home/ben/src/forks/opentelemetry-python-contrib/_e/lib64/python3.12/site-packages/yarl/_url.py", line 1607, in _host_validate
    raise ValueError(
ValueError: Host '127.0.0.1:33779' cannot contain ':' (at position 9)
================================================ warnings summary ================================================
[omitted for brevity]
==================================== 1 failed, 32 passed, 4 warnings in 5.54s ====================================
```

### Additional context

Further investigation shows that the regression is also present in `yarl` 1.13.0, so it first appeared in that release.

I don’t see any obvious, intentional changes that seem relevant in the changelogs: https://github.com/aio-libs/yarl/blob/v1.15.5/CHANGES.rst#1130

The source diff between those releases is relatively small: https://github.com/aio-libs/yarl/compare/v1.12.1...v1.13.0

At this time, I’m not planning to offer a PR for this because I don’t understand the root cause, so I am not quite sure what should be changed.

### Would you like to implement a fix?

No

**Comment by musicinmybrain** [comment]
This does seem to be related to https://github.com/aio-libs/yarl/pull/954, in which `:` is now rejected as part of an ASCII hostname. 

I found that there are similar failures in the tests for `opentelemetry-instrumentation-aiohttp-server`.

More importantly, considering https://github.com/aio-libs/yarl/pull/954 together with the traceback lead me to suspect that the problem was actually in `aiohttp`, and I discovered that upgrading it to 3.10.7 or later solves the problem – so it appears there is nothing to be done here.
