### ISSUE TITLE
[FastAPI] exception handler always has span_id is 0

### ISSUE THREAD

**Issue by sdg9670f** [open-telemetry/opentelemetry-python-contrib#3007]
### Describe your environment

OS: Ubuntu
Python version: 3.12

### What happened?

When an exception is raised and handled by the `exception_handler`, the `span_id` printed is always 0. However, the `span_id`printed in the middleware is correct.

### Steps to Reproduce

```python
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from fastapi.responses import JSONResponse
from fastapi import FastAPI, Request
from opentelemetry.trace import get_current_span
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter

otlp_url = 'http://localhost:4317'

trace.set_tracer_provider(TracerProvider())
span_exporter = OTLPSpanExporter(endpoint=otlp_url)
span_processor = BatchSpanProcessor(span_exporter)
trace.get_tracer_provider().add_span_processor(span_processor)


app = FastAPI()


@app.exception_handler(Exception)
def exception_handler(request: Request, exception: Exception):
    print('exception_handler', get_current_span().get_span_context().span_id)

    return JSONResponse(
        status_code=500,
        content={"message": "Internal server error"},
    )


@app.middleware("http")
async def middleware(request: Request, call_next):
    print('middleware', get_current_span().get_span_context().span_id)

    response = await call_next(request)
    return response


@app.get("/")
def read_root():
    raise Exception("error")


FastAPIInstrumentor.instrument_app(app)

```

### Expected Result

middleware 1234
exception_handler 1234

### Actual Result

middleware 1234
exception_handler 0

### Would you like to implement a fix?

None

**Comment by niehongxu116** [comment]
You can pay attention to the registration order of fastApi's middleware and the way it captures exceptions. The source code is as above. Although you have registered the handling method for Exception exceptions, the source code has processed them. Capture and processing occur in ServerError Middleware, not in the user_midddware you expected. Therefore, trace and span IDs cannot be obtained in the processing function you defined.

```
    def build_middleware_stack(self) -> ASGIApp:
        debug = self.debug
        error_handler = None
        exception_handlers: dict[typing.Any, typing.Callable[[Request, Exception], Response]] = {}

        for key, value in self.exception_handlers.items():
            if key in (500, Exception):
                error_handler = value
            else:
                exception_handlers[key] = value

        middleware = (
            [Middleware(ServerErrorMiddleware, handler=error_handler, debug=debug)]
            + self.user_middleware
            + [Middleware(ExceptionMiddleware, handlers=exception_handlers, debug=debug)]
        )

        app = self.router
        for cls, args, kwargs in reversed(middleware):
            app = cls(app, *args, **kwargs)
        return app
```

To solve the above problems, you can use

```
from opentelemetry.instrumentation.asgi import OpenTelemetryMiddleware
asgi_app = OpenTelemetryMiddleware(
    app,
    tracer_provider=tracer,
    excluded_urls=parse_excluded_urls("metrics,health")
)
```

The above is my personal opinion, hoping it will be helpful to you！

**Comment by tuukkamustonen** [comment]
See https://github.com/open-telemetry/opentelemetry-python/issues/3477

**Comment by mcleantom** [comment]
I am still getting an issue with this, in this example app:

```python
from fastapi import FastAPI, Request
from opentelemetry.exporter.otlp.proto.grpc import trace_exporter
from opentelemetry.instrumentation.asgi import OpenTelemetryMiddleware
from opentelemetry.sdk.resources import Resource
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
from opentelemetry.instrumentation.logging import LoggingInstrumentor
from opentelemetry.instrumentation.requests import RequestsInstrumentor
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from starlette.responses import JSONResponse
import logging, os

# Setup OpenTelemetry
resource = Resource.create(attributes={"service.name": os.environ["SERVICE_NAME"]})
trace_provider = TracerProvider(resource=resource)
trace.set_tracer_provider(trace_provider)
trace_provider.add_span_processor(
    BatchSpanProcessor(OTLPSpanExporter(insecure=True))
)

LoggingInstrumentor().instrument()
RequestsInstrumentor().instrument()

# Define FastAPI app
app = FastAPI()

@app.get("/throws")
async def throws():
    raise ValueError("Oops!")

@app.get("/ok")
async def ok():
    return {"message": "Fine"}

@app.exception_handler(Exception)
async def handle_all_exceptions(request: Request, exc: Exception):
    logging.exception("Handled exception", exc_info=exc)
    return JSONResponse(content={"detail": "Internal Server Error"}, status_code=500)

FastAPIInstrumentor().instrument_app(app)
asgi_app = OpenTelemetryMiddleware(app, tracer_provider=trace_provider)
```

if I go to the `/throws` endpoint, I can see one log message from the custom exception handler with the trace id, then another exception message from uvicorn without the trace id:

```
fastapi-app-1  | 2025-07-31 08:10:22,886 INFO [uvicorn.error] [server.py:84] [trace_id=0 span_id=0 resource.service.name=fastapi-app-1] - Started server process [1]
fastapi-app-1  | 2025-07-31 08:10:22,887 INFO [uvicorn.error] [on.py:48] [trace_id=0 span_id=0 resource.service.name=fastapi-app-1] - Waiting for application startup.
fastapi-app-1  | 2025-07-31 08:10:22,887 INFO [uvicorn.error] [on.py:62] [trace_id=0 span_id=0 resource.service.name=fastapi-app-1] - Application startup complete.
fastapi-app-1  | 2025-07-31 08:10:22,887 INFO [uvicorn.error] [server.py:216] [trace_id=0 span_id=0 resource.service.name=fastapi-app-1] - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
fastapi-app-1  | 2025-07-31 08:10:24,315 ERROR [root] [main.py:41] [trace_id=01475de07b3933590da528898e0d14a9 span_id=355c87a166b5f480 resource.service.name=fastapi-app-1] - Handled exception
fastapi-app-1  | Traceback (most recent call last):
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
fastapi-app-1  |     await self.app(scope, receive, _send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
fastapi-app-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
fastapi-app-1  |     raise exc
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
fastapi-app-1  |     await app(scope, receive, sender)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 716, in __call__
fastapi-app-1  |     await self.middleware_stack(scope, receive, send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 736, in app
fastapi-app-1  |     await route.handle(scope, receive, send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 290, in handle
fastapi-app-1  |     await self.app(scope, receive, send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 78, in app
fastapi-app-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
fastapi-app-1  |     raise exc
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
fastapi-app-1  |     await app(scope, receive, sender)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
fastapi-app-1  |     response = await f(request)
fastapi-app-1  |                ^^^^^^^^^^^^^^^^
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 302, in app
fastapi-app-1  |     raw_response = await run_endpoint_function(
fastapi-app-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
fastapi-app-1  |     return await dependant.call(**values)
fastapi-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-app-1  |   File "/app/main.py", line 33, in throws
fastapi-app-1  |     raise ValueError("Oops!")
fastapi-app-1  | ValueError: Oops!
fastapi-app-1  | 2025-07-31 08:10:24,318 INFO [uvicorn.access] [h11_impl.py:473] [trace_id=01475de07b3933590da528898e0d14a9 span_id=355c87a166b5f480 resource.service.name=fastapi-app-1] - 192.168.97.1:38576 - "GET /throws HTTP/1.1" 500
fastapi-app-1  | 2025-07-31 08:10:24,319 ERROR [uvicorn.error] [h11_impl.py:408] [trace_id=0 span_id=0 resource.service.name=fastapi-app-1] - Exception in ASGI application
fastapi-app-1  | Traceback (most recent call last):
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
fastapi-app-1  |     result = await app(  # type: ignore[func-returns-value]
fastapi-app-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
fastapi-app-1  |     return await self.app(scope, receive, send)
fastapi-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 768, in __call__
fastapi-app-1  |     await self.app(scope, otel_receive, otel_send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
fastapi-app-1  |     await super().__call__(scope, receive, send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
fastapi-app-1  |     await self.middleware_stack(scope, receive, send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
fastapi-app-1  |     raise exc
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
fastapi-app-1  |     await self.app(scope, receive, _send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 768, in __call__
fastapi-app-1  |     await self.app(scope, otel_receive, otel_send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
fastapi-app-1  |     raise exc
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
fastapi-app-1  |     await self.app(scope, receive, _send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
fastapi-app-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
fastapi-app-1  |     raise exc
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
fastapi-app-1  |     await app(scope, receive, sender)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 716, in __call__
fastapi-app-1  |     await self.middleware_stack(scope, receive, send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 736, in app
fastapi-app-1  |     await route.handle(scope, receive, send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 290, in handle
fastapi-app-1  |     await self.app(scope, receive, send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 78, in app
fastapi-app-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
fastapi-app-1  |     raise exc
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
fastapi-app-1  |     await app(scope, receive, sender)
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
fastapi-app-1  |     response = await f(request)
fastapi-app-1  |                ^^^^^^^^^^^^^^^^
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 302, in app
fastapi-app-1  |     raw_response = await run_endpoint_function(
fastapi-app-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-app-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
fastapi-app-1  |     return await dependant.call(**values)
fastapi-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-app-1  |   File "/app/main.py", line 33, in throws
fastapi-app-1  |     raise ValueError("Oops!")
fastapi-app-1  | ValueError: Oops!
```

My app was created with docker with this Dockerfile:
```
FROM python:3.11

WORKDIR /app

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./main.py ./
COPY ./utils.py ./
COPY ./log-format.yaml ./

CMD ["uvicorn", "main:asgi_app", "--host", "0.0.0.0", "--port", "8000", "--log-config", "log-format.yaml"]
```

And this logging config:
```
version: 1
formatters:
  default:
    format: "%(asctime)s %(levelname)s [%(name)s] [%(filename)s:%(lineno)d] [trace_id=%(otelTraceID)s span_id=%(otelSpanID)s resource.service.name=%(otelServiceName)s] - %(message)s"
    use_colors: true
  access:
    format: "%(asctime)s %(levelname)s [%(name)s] [%(filename)s:%(lineno)d] [trace_id=%(otelTraceID)s span_id=%(otelSpanID)s resource.service.name=%(otelServiceName)s] - %(message)s"
handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stderr
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no
root:
  level: DEBUG
  handlers:
    - default
  propagate: no
```

Any ideas why the trace id is not kept on the logs?
