### ISSUE TITLE
[redis] Redis-sentinel not working

### ISSUE THREAD

**Issue by vtdat** [open-telemetry/opentelemetry-python-contrib#304]
The Redis auto instrumentation is not working with redis-sentinel

**Steps to reproduce**
Setup a redis-sentinel and a redis instance, run an application with sentinel configurations.

**What is the expected behavior?**
Information for sentinel connections

**What is the actual behavior?**
```
"Traceback (most recent call last):
  File "/home/vutuandat/.local/share/project_name-tNQ0Wzfa/lib/python3.8/site-packages/opentelemetry/instrumentation/redis/util.py", line 29, in _extract_conn_attributes
    attributes["net.peer.name"] = conn_kwargs["host"]
KeyError: 'host'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vutuandat/.local/share/project_name-tNQ0Wzfa/lib/python3.8/site-packages/opentelemetry/sdk/trace/__init__.py", line 861, in use_span
    yield span
  File "/home/vutuandat/.local/share/project_name-tNQ0Wzfa/lib/python3.8/site-packages/opentelemetry/sdk/trace/__init__.py", line 774, in start_as_current_span
    yield span_context
  File "/home/vutuandat/.local/share/project_name-tNQ0Wzfa/lib/python3.8/site-packages/opentelemetry/instrumentation/redis/__init__.py", line 84, in _traced_execute_command
    _set_connection_attributes(span, instance)
  File "/home/vutuandat/.local/share/project_name-tNQ0Wzfa/lib/python3.8/site-packages/opentelemetry/instrumentation/redis/__init__.py", line 64, in _set_connection_attributes
    for key, value in _extract_conn_attributes(
  File "/home/vutuandat/.local/share/project_name-tNQ0Wzfa/lib/python3.8/site-packages/opentelemetry/instrumentation/redis/util.py", line 33, in _extract_conn_attributes
    attributes["net.peer.name"] = conn_kwargs["path"]
KeyError: 'path'
"```

**Additional context**

python 3.8.5
opentelemetry-sdk 0.17b0
opentelemetry-instrumentation-redis 0.17b0

I did manage to make it run by adding 

```python
        try:
            attributes["net.peer.name"] = conn_kwargs["path"]
            attributes["net.transport"] = "Unix"
        except KeyError:
            attributes["net.peer.name"] = conn_kwargs["connection_pool"].service_name
            ...
```

to https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/instrumentation/opentelemetry-instrumentation-redis/src/opentelemetry/instrumentation/redis/util.py#L33

however, I'm not sure which information we want to put in span tags.

**Comment by lonewolf3739** [comment]
Same as #389

**Comment by ocelotl** [comment]
I asked Claude to review this issue and Claude suggests it be closed with this explanation:

> `KeyError: 'host'` fixed; `_extract_conn_attributes` now defaults host/port and handles unix sockets.
>
> Proof in `main`: [`redis/util.py#L60-L77`](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/94e851dfe333d47fdb52edb82635330668af284e/instrumentation/opentelemetry-instrumentation-redis/src/opentelemetry/instrumentation/redis/util.py#L60-L77)

To guard against a mistaken suggestion, Claude then independently re-verified this conclusion:

> Verified: `_extract_conn_attributes` in `redis/util.py` now reads host/port defensively with `.get(...)` defaults and handles unix sockets, so the sentinel `KeyError` no longer occurs.

Claude evaluated this issue with high confidence that it can be closed.

Claude has classified this issue as already resolved (the requested fix or feature has already shipped).

The intention of this comment is to make it easier for a human being to review this issue before making a decision.
