### ISSUE TITLE
aiohttp_server auto instrumentation make app crash with 500 if port in Host header

### ISSUE THREAD

**Issue by babs** [open-telemetry/opentelemetry-python-contrib#3044]
### Describe your environment

OS: Ubuntu
Python version: 3.12.3
Package version: 0.49b2

### What happened?

When enabling autoinstrumentation of an aiohttp_server app, if the request comes with the Host header containing port, it makes the app return 500 errors.
If run without auto instrumentation, it works fine.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host

### Steps to Reproduce

Take any aiohttp_server auto instrumented code and call it using curl with:
```bash
curl -H Host:\ localhost:80 http://localhost
```

### Expected Result

I'd expect the request to work

### Actual Result

500 response

### Would you like to implement a fix?

None

**Comment by babs** [comment]
I've tracked it to:

```
Traceback (most recent call last):
  File ".venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/opentelemetry/instrumentation/aiohttp_server/__init__.py", line 198, in middleware
    request.url
  File "aiohttp/_helpers.pyx", line 26, in aiohttp._helpers.reify.__get__
  File ".venv/lib/python3.12/site-packages/aiohttp/web_request.py", line 453, in url
    url = URL.build(scheme=self.scheme, host=self.host)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/yarl/_url.py", line 386, in build
    _host = _encode_host(host, validate_host=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/yarl/_url.py", line 1496, in _encode_host
    raise ValueError(
ValueError: Host 'localhost:80' cannot contain ':' (at position 9)
```

**Comment by babs** [comment]
I've *workarounded* it by editing `aiohttp/web_request.py`'s `BaseRequest.host` function and addint a split on ":" and taking the first portion, but it requires a more clever approach for IPv6 addresses.

```python
    @reify
    def host(self) -> str:
        """Hostname of the request.

        Hostname is resolved in this order:

        - overridden value by .clone(host=new_host) call.
        - HOST HTTP header
        - socket.getfqdn() value
        """
        host = self._message.headers.get(hdrs.HOST).split(":")[0]
        if host is not None:
            return host
        return socket.getfqdn()
```


Should I open this issue on https://github.com/aio-libs/aiohttp ?

**Comment by babs** [comment]
Ok I've trackend down further.
I can't reproduce the issue on aiohttp-3.11.7, and aiohttp-3.10.5 is set as a dependency of the original `botbuilder-integration-aiohttp`... I think it's time for me to open the issue on microsoft botbuilder repo to ask for dependency update :)
