### ISSUE TITLE
RecursionError generated on heavily loaded service/database

### ISSUE THREAD

**Issue by withnale** [open-telemetry/opentelemetry-python-contrib#335]
**Describe your environment** 

Using python 3.7.3
opentelemetry-instrumentation-psycopg2 0.17b0

**Steps to reproduce**
Our application makes heavy use of the pandas library and uses very complex queries in the SQL calls. The majority of the
time these work fine as expected, but when the application and/or database is under load we sometimes get a number of `RecursionError: maximum recursion depth exceeded in comparison` exceptions generated.

These only occur when `Psycopg2Instrumentor().instrument()` is specified - these steps go through normally if instrumentation isn't enabled.

**What is the expected behavior?**
The application should run to completion normally, as it does when `Psycopg2Instrumentor().instrument()` is absent.

**What is the actual behavior?**

Errors similar to the following occur.

```
API EXCEPTION: code: 'unrecognized_exception' description: Unrecognized exception
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/pandas/io/sql.py", line 1595, in execute
    cur.execute(*args)
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/psycopg2/__init__.py", line 167, in execute
    self, super().execute, *args, **kwargs
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 392, in traced_execution
    raise ex
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 387, in traced_execution
    result = query_method(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/psycopg2/__init__.py", line 167, in execute
    self, super().execute, *args, **kwargs
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 392, in traced_execution
    raise ex
  .... 1400 repeating lines deleted ....
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 392, in traced_execution
    raise ex
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 387, in traced_execution
    result = query_method(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/psycopg2/__init__.py", line 167, in execute
    self, super().execute, *args, **kwargs
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 383, in traced_execution
    name, kind=SpanKind.CLIENT
  File "/opt/python3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/env/lib/python3.7/site-packages/opentelemetry/sdk/trace/__init__.py", line 771, in start_as_current_span
    set_status_on_exception=set_status_on_exception,
  File "/env/lib/python3.7/site-packages/opentelemetry/sdk/trace/__init__.py", line 816, in start_span
    context, trace_id, name, attributes, links, trace_state
  File "/env/lib/python3.7/site-packages/opentelemetry/sdk/trace/sampling.py", line 300, in should_sample
    parent_context
  File "/env/lib/python3.7/site-packages/opentelemetry/trace/propagation/__init__.py", line 48, in get_current_span
    if span is None or not isinstance(span, Span):
  File "/opt/python3.7/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmagent/app/pp/db.py", line 179, in read_sql_query
    return pd.read_sql_query(sql=sql_query, con=conn, params=params)
  File "/env/lib/python3.7/site-packages/pandas/io/sql.py", line 332, in read_sql_query
    chunksize=chunksize,
  File "/env/lib/python3.7/site-packages/pandas/io/sql.py", line 1645, in read_query
    cursor = self.execute(*args)
  File "/env/lib/python3.7/site-packages/pandas/io/sql.py", line 1610, in execute
    raise_with_traceback(ex)
  File "/env/lib/python3.7/site-packages/pandas/compat/__init__.py", line 47, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/env/lib/python3.7/site-packages/pandas/io/sql.py", line 1595, in execute
    cur.execute(*args)
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/psycopg2/__init__.py", line 167, in execute
    self, super().execute, *args, **kwargs
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 392, in traced_execution
    raise ex
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 387, in traced_execution
    result = query_method(*args, **kwargs)
  ... 1400 repeated lines ...
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 392, in traced_execution
    raise ex
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 387, in traced_execution
    result = query_method(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/psycopg2/__init__.py", line 167, in execute
    self, super().execute, *args, **kwargs
  File "/env/lib/python3.7/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 383, in traced_execution
    name, kind=SpanKind.CLIENT
  File "/opt/python3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/env/lib/python3.7/site-packages/opentelemetry/sdk/trace/__init__.py", line 771, in start_as_current_span
    set_status_on_exception=set_status_on_exception,
  File "/env/lib/python3.7/site-packages/opentelemetry/sdk/trace/__init__.py", line 816, in start_span
    context, trace_id, name, attributes, links, trace_state
  File "/env/lib/python3.7/site-packages/opentelemetry/sdk/trace/sampling.py", line 300, in should_sample
    parent_context
  File "/env/lib/python3.7/site-packages/opentelemetry/trace/propagation/__init__.py", line 48, in get_current_span
    if span is None or not isinstance(span, Span):
  File "/opt/python3.7/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
pandas.io.sql.DatabaseError: Execution failed on sql 'REDACTED SQL QUERY': maximum recursion depth exceeded in comparison
```

**Comment by owais** [comment]
@withnale Thanks for reporting this. It'd be really nice if you could share a minimal demo app with us that we could use to reproduce the issue with. Thanks.

**Comment by withnale** [comment]
Hello. I think we've got to the bottom of it.

For some reason we had our DB calls in a try/except block and when it failed the except block would call method again with a retry counter. It was a bit weird but hadn't caused us any problems up until now. However, I'm sure it would be likely to cause the autoinstrumentation some problems.

**Comment by owais** [comment]
Sounds good. Should we close this issue then?

**Comment by withnale** [comment]
Yes. That's fine.
