### ISSUE TITLE
Latest versions of instrumentations are broken 

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-python-contrib#346]
I just tried to setup an example project from scratch and looks like some instrumentations are broken right now. I tested with falcon but I think flask, pyramid and some others are affected as well. 

**Describe your environment** 

Python 3.7 on macOS.

**Steps to reproduce**

1. Install the following packages:

```
pip install falcon opentelemetry-api opentelemetry-sdk opentelemetry-instrumentation-falcon opentelemetry-distro opentelemetry-exporter-otlp
```

2.  Save the following falcon app as `main.py`

```python
import json

import falcon
from wsgiref import simple_server

class HelloWorldResource(object):
    def on_get(self, req, resp):
        resp.body = json.dumps({'ok': True})


app = falcon.API()
app.add_route('/hello', HelloWorldResource())

if __name__ == '__main__':
    port = 8000
    httpd = simple_server.make_server('127.0.0.1', port, app)
    httpd.serve_forever()
```

3. Run the app with opentelemetry-instrument

```
> opentelemetry-instrument ./main.py
Instrumenting of falcon failed
Traceback (most recent call last):
  File "/Users/olone/playground/otelfalcon/venv/lib/python3.7/site-packages/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 56, in _load_instrumentors
    entry_point.load()().instrument()  # type: ignore
  File "/Users/olone/playground/otelfalcon/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/Users/olone/playground/otelfalcon/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/olone/playground/otelfalcon/venv/lib/python3.7/site-packages/opentelemetry/instrumentation/falcon/__init__.py", line 61, in <module>
    from opentelemetry.util.providers import time_ns
ModuleNotFoundError: No module named 'opentelemetry.util.providers'
Failed to auto initialize opentelemetry
Traceback (most recent call last):
  File "/Users/olone/playground/otelfalcon/venv/lib/python3.7/site-packages/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 85, in initialize
    _load_instrumentors()
  File "/Users/olone/playground/otelfalcon/venv/lib/python3.7/site-packages/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 60, in _load_instrumentors
    raise exc
  File "/Users/olone/playground/otelfalcon/venv/lib/python3.7/site-packages/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 56, in _load_instrumentors
    entry_point.load()().instrument()  # type: ignore
  File "/Users/olone/playground/otelfalcon/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/Users/olone/playground/otelfalcon/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/olone/playground/otelfalcon/venv/lib/python3.7/site-packages/opentelemetry/instrumentation/falcon/__init__.py", line 61, in <module>
    from opentelemetry.util.providers import time_ns
ModuleNotFoundError: No module named 'opentelemetry.util.providers'
```

**What is the expected behavior?**
For the instrumentation to not crash with ModuleNotFoundError

**What is the actual behavior?**
ModuleNotFoundError raised by falcon instrumentation as it complains it cannot find `opentelemetry.util.providers`

**Additional context**

```
> pip freeze
asgiref==3.3.1
backoff==1.10.0
falcon==2.0.0
googleapis-common-protos==1.52.0
grpcio==1.35.0
opentelemetry-api==1.0.0rc1
opentelemetry-distro==0.18b0
opentelemetry-exporter-otlp==1.0.0rc1
opentelemetry-instrumentation==0.18b0
opentelemetry-instrumentation-falcon==0.18b0
opentelemetry-instrumentation-wsgi==0.18b0
opentelemetry-proto==1.0.0rc1
opentelemetry-sdk==1.0.0rc1
opentelemetry-util-http==0.18b0
protobuf==3.15.0
six==1.15.0
wrapt==1.12.1
```

**Comment by owais** [comment]
I think you're most familiar with the "utils.providers" packages so assigned to you. Please feel free to re-assign.

**Comment by owais** [comment]
It looks like this providers code was added recently and did not make it into the opentelemetry-api package on pypi but instrumentations were published after this was added to core. 

If this is the case, we should release a hotfix for opentelemetry-api package to "unbreak" these instrumentations. 


This also brings up the questions about why CI did not catch this. I think pypi release job should test against pypi packages instead of pulling in core from git. That would probably have caught this when instrumentations were released.

//cc @lzchen @codeboten

**Comment by lzchen** [comment]
> This also brings up the questions about why CI did not catch this.
I think having the commit hash set to the branch that is going to be released is sufficient. I just made the mistake of merging a change in and releasing core and not rerunning contrib before releasing. Will be creating a hotfix to revert contrib changes.

**Comment by lzchen** [comment]
Should be fixed with https://github.com/open-telemetry/opentelemetry-python-contrib/releases/tag/v0.18b1

**Comment by owais** [comment]
Fix verified. Thanks @lzchen
