### ISSUE TITLE
FastApi Opentelemetry throwing concurrent.futures._base.CancelledError 

### ISSUE THREAD

**Issue by nilansaha** [open-telemetry/opentelemetry-python-contrib#467]
For Kubernetes I have implemented healthchecks in FastAPI like this

```
@router.get("/health/liveness", tags=["health_checks"])
async def liveness():
    if check_liveness():
        result = {"status": "UP"}
    else:
        result = {"result": "DOWN"}
    return result
```

However, opentelemetry always gives errors in these spans. Not sure why. This is the error I get in Datadog Tracing
```
CancelledError
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/opentelemetry/trace/__init__.py", line 522, in use_span
yield span
File "/usr/local/lib/python3.7/site-packages/opentelemetry/sdk/trace/__init__.py", line 879, in start_as_current_span
yield span_context
File "/usr/local/lib/python3.7/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 213, in wrapped_receive
message = await receive()
File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 526, in receive
await self.message_event.wait()
File "/usr/local/lib/python3.7/asyncio/locks.py", line 293, in wait
await fut
concurrent.futures._base.CancelledError
```

And this happens for all the endpoints. Not sure whats up. Any help is appreciated.

**Comment by cdvv7788** [comment]
https://github.com/cdvv7788/fastapi_instrumentation_bug I created this repository to reproduce the bug.
Basically you need to move the instrumentation before all of the other middlewares so it is evaluated last (it seems fastapi evaluates middlewares in reverse order). For some reason, the asgi instrumentation is creating additional traces when adding middlewares, which causes this issue to occur.
I don't have much context to know exactly what is happening, but you can reproduce it now.

**Comment by cdvv7788** [comment]
@nilansaha @thaodt This issue is still active. Any ideas to get it solved?

**Comment by Blueswen** [comment]
I think CancelledError exception is a bug in [asyncio](https://github.com/python/cpython/blob/3.7/Lib/asyncio/locks.py) module of python 3.7.  If you using higher version than 3.7 CancelledError problem will be solved. This bug is fix in python 3.8 with this [commit](https://github.com/python/cpython/commit/2f79c014931cbb23b08a7d16c534a3cc9607ae14), where they use another try  to deal with the CancelledError(line 191 of locks.py).

I have the same bug when using fastAPI which has another middleware with opentelemetry manual instrumentation in python 3.7.13. But when I change to python 3.8.13 and python 3.9.12, everything is fine.

**Comment by ocelotl** [comment]
I asked Claude to review this issue and Claude suggests it be closed with this explanation:

> No activity since 2022-04 on v0.20b0; receive-span path reworked and now optional.
>
> Proof in `main`: — (stale)

To guard against a mistaken suggestion, Claude then independently re-verified this conclusion:

> Verified: there has been no activity since 2022-04 on v0.20b0, the `CancelledError` was diagnosed as a Python 3.7 asyncio bug, and the receive-span path is now optional via `exclude_spans`.

Claude evaluated this issue with medium confidence that it can be closed.

Claude has classified this issue as stale (abandoned, low-value, or with no path forward).

The intention of this comment is to make it easier for a human being to review this issue before making a decision.
